/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AppendArchiveOptions {
  /** Existing RAR5 archive to append to (single-volume only). */
  archivePath: string
  entries: Array<EntryInput>
  /** Compression level 0..=5 (default 3). */
  level?: number
  /**
   * Password of the existing archive (needed when its content is
   * encrypted so the solid chain can be extended).
   */
  password?: string
}

/**
 * Append entries to an existing RAR5 archive without rebuilding it.
 *
 * Existing members are preserved verbatim (never recompressed); only the
 * trailing quick-open/recovery/end blocks are truncated and rewritten.
 * Recovery records are regenerated over the whole archive. Multi-volume
 * archives are not supported (matching the official `rar` CLI).
 */
export declare function appendEntries(opts: AppendArchiveOptions, onProgress?: (((err: Error | null, arg: ProgressData) => void)) | undefined | null, signal?: AbortSignal | undefined | null): Promise<CreateResult>

/** Create a RAR5 archive from the given entries. */
export declare function createArchive(opts: CreateArchiveOptions, onProgress?: (((err: Error | null, arg: ProgressData) => void)) | undefined | null, signal?: AbortSignal | undefined | null): Promise<CreateResult>

export interface CreateArchiveOptions {
  outPath: string
  entries: Array<EntryInput>
  /** Compression level 0..=5 (default 3). */
  level?: number
  /** Optional AES-256 password (file-level encryption). */
  password?: string
  /**
   * Also encrypt the archive structure (file names) — RAR5 header
   * encryption. Requires `password`; incompatible with multi-volume.
   */
  encryptHeaders?: boolean
  /**
   * Add a WinRAR-compatible inline recovery record protecting this percent
   * (0-100) of the archive. Incompatible with multi-volume.
   */
  recoveryPercent?: number
  /**
   * Create this many `.rev` recovery volumes (WinRAR `-rv`); auto-capped
   * at the actual data volume count. Requires `volume_size`.
   */
  recoveryVolumeCount?: number
  /**
   * Volume size in bytes; when set, produces multi-volume archives
   * (`name.part1.rar`, ...).
   */
  volumeSize?: number
  /** Reject the operation when the summed input size exceeds this. */
  maxTotalBytes?: number
}

export interface CreateResult {
  /** Paths of all files produced (single archive or volumes). */
  files: Array<string>
}

/**
 * Delete members from a RAR5 archive without rebuilding it.
 *
 * Non-solid archives are rewritten surgically: kept members are copied
 * verbatim, never recompressed (like the official `rar d`). Solid chains
 * that lose a member are recompressed from the chain start only. For
 * multi-volume archives, kept payloads are re-split at the volume size
 * limit and `.rev` recovery volumes are regenerated.
 *
 * Fails when any requested name is not present, or when the archive is
 * locked. Returns the number of deleted members.
 */
export declare function deleteEntries(archivePath: string, names: Array<string>, password?: string | undefined | null): number

export interface EntryInput {
  /** "file" | "dir" | "bytes" */
  kind: string
  /** Filesystem path for "file" and "dir" entries. */
  path?: string
  /**
   * Archive entry name. For "file"/"dir" defaults to the basename, for
   * "bytes" it is required.
   */
  name?: string
  /** Byte payload for "bytes" entries. */
  data?: Buffer
}

export interface ProgressData {
  done: number
  total: number
}

/**
 * Rebuild missing volumes of a multi-volume RAR5 set from its `.rev`
 * recovery volumes (like WinRAR `rc`).
 *
 * `first_volume` is the path of `name.part1.rar`; every missing volume is
 * reconstructed from the `.rev` parity volumes into the same directory.
 * Returns the paths of all volumes produced.
 */
export declare function rebuildMissingVolumes(firstVolume: string): Array<string>

/**
 * Repair a damaged RAR5 archive using its inline recovery record.
 *
 * Reads `input_path`, rebuilds any damaged data shards from the `{RB}`
 * parity shards and writes the repaired archive to `output_path`.
 */
export declare function repairArchive(inputPath: string, outputPath: string): void
