/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Create a RAR5 archive from the given entries. */
export declare function createArchive(opts: CreateArchiveOptions, onProgress?: (((err: Error | null, arg: ProgressData) => void)) | undefined | null, signal?: AbortSignal | undefined | null): Promise<CreateResult>

export interface CreateArchiveOptions {
  outPath: string
  entries: Array<EntryInput>
  /** Compression level 0..=5 (default 3). */
  level?: number
  /** Optional AES-256 password (file-level encryption). */
  password?: string
  /**
   * Volume size in bytes; when set, produces multi-volume archives
   * (`name.part1.rar`, ...).
   */
  volumeSize?: number
  /** Reject the operation when the summed input size exceeds this. */
  maxTotalBytes?: number
}

export interface CreateResult {
  /** Paths of all files produced (single archive or volumes). */
  files: Array<string>
}

export interface EntryInput {
  /** "file" | "dir" | "bytes" */
  kind: string
  /** Filesystem path for "file" and "dir" entries. */
  path?: string
  /**
   * Archive entry name. For "file"/"dir" defaults to the basename, for
   * "bytes" it is required.
   */
  name?: string
  /** Byte payload for "bytes" entries. */
  data?: Buffer
}

export interface ProgressData {
  done: number
  total: number
}
